### ISSUE TITLE
Foundation asset 세팅

### ISSUE THREAD

**Issue by dong-fa** [pie-sfac/3-20-gangstarr#2]
완성되면 커밋 후 체크 바랍니다.
------------
- [x] 컬러 - 정연우
- [x] 타이포그래피 - 홍성인
- [x] 아이콘 - 최동환
- [x] 그래픽 - 김준경

**Comment by sungin46** [comment]
다들 수고하셨읍니다.

**Comment by sungin46** [comment]
오타 수정되어 다시 오픈합니다.
