### ISSUE TITLE
README 작성

### ISSUE THREAD

**Issue by 0SCAR0421** [pie-sfac/3-20-gangstarr#78]
- [x] 홍성인 
- [x] 김준경
- [x] 정연우
- [x] 최동환

작성완료되면 reademe 브랜치에 push 해주시고 체크 버튼을 눌러주세요!
팀원들에게 작성이 완료됐다고 알려주세요.

**Comment by sungin46** [comment]
README.md 작성 끝났으므로 이슈 닫겠습니다.
